### ISSUE TITLE
Flesh out README

### ISSUE THREAD

**Issue by avisionh** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#18]
Describe how to set-up this repo when someone clones it.

This includes:
1. `git clone ...`
1. `renv::restore()`
etc.

**Comment by martinctc** [comment]
I think a contributor guide would also be useful, though we can discuss whether this should be part of the README or can just exist in the GitHub Wiki?

**Comment by avisionh** [comment]
Good point, I was reading about this before actually and it seems standard practice to add this as a separate `.md` in the `.docs/` folder.

https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
