### ISSUE TITLE
Select by region

### ISSUE THREAD

**Issue by avisionh** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#25]
Some people do not know what district they belong to so enable them to guess better by enabling ability filter dropdown by region such as *New Territories*, *Kowloon* etc.

**Comment by avisionh** [comment]
Linked to #35. Makes sense to resolve them both together.

**Comment by avisionh** [comment]
Having optional and dependent search boxes aren't super easy! The below doesn't work.

```
selectizeInput(inputId = "input_dropdowntext",
                       label = "請選擇選區 / Please type or select a district",
                       choices = list(Region = sort(unique(data_master_raw$Region)),
                                      Constituency = sort(unique(data_master_raw$DropDownText)),
                                      DC = sort(unique(data_master_raw$DC)))
                       ), #selectizeInput
```

![image](https://user-images.githubusercontent.com/25527485/89127842-d8061580-d4e8-11ea-99e9-8b50bc4a3443.png)

**Comment by avisionh** [comment]
Made this a *spike* because what you want is different ways to filter, but at the same time, these filters can impact the choices in a different filter *e.g. Someone chooses  `Region = "Hong Kong Islands"` and then the list of DCs becomes smaller.

From previous experience in my old company, this was quite difficult to achieve.

**Comment by ocean0609** [comment]
We should add a filter for "District" before "Constituency"
Capscreen from MyMapHK, Mobile Map App by HK Gov's Lands Dept
![IMG_6630](https://user-images.githubusercontent.com/67370580/89486016-a3d67180-d7d4-11ea-8b70-42cd1d27b49c.PNG)
![IMG_6631](https://user-images.githubusercontent.com/67370580/89486024-a638cb80-d7d4-11ea-8971-e10e70c13922.PNG)
