### ISSUE TITLE
Feature: Include Chinese translations

### ISSUE THREAD

**Issue by avisionh** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#32]
**Is your feature request related to a problem? Please describe.**
As a Chinese language user, I want to be able access the website in Chinese.

**Describe the solution you'd like**
Chinese translation of everything that's already in English.

**Describe alternatives you've considered**
Whilst most can speak English, having Chinese will improve the reach of this website.

**Additional context**

**Comment by avisionh** [comment]
From @ocean0609:

***

使用條款 Terms of Use

 您了解以下內容適用於本網站：
You understand that the following applies to this website:

本網站不隸屬於任何政治人物或運動。
 We are not affiliated to any political individuals nor movements.

本網站對任何潛在的濫用不承擔任何責任。
 We are not liable for any potential misuses.

本網站使用跟踪cookie為您提供最佳的在線體驗 
We use tracking cookies to give you the best online experience.

如要繼續使用本網站，即表示您同意以上使用條款。
By proceeding further, you are agreeing to these Terms of Use.

 您願意繼續並啟用跟踪Cookie嗎？
Do you want to proceed and have tracking cookies enabled?  

是/否
Yes/No  提交 Submit Choice

**Comment by avisionh** [comment]
From @justin-yim:
***
https://docs.google.com/document/d/1SUoAarLCXYZC9XY5vOtUjFOM97HOt1IoUl5A4SkdzAs/

**Comment by ocean0609** [comment]
Tab:
Overview of a DC 區議員簡介
List of DCs 區議員目錄
Construction < is it the accurate name for tab? or should we use “Further Information”?
*This app uses data from: Google Sheet of HK DCs < need to update @martinctc 

Region 地區
District 區
Constituency 選區
DC 區議員

Show__ entries  顯視 __ 條目 (All 所有)
Search: 搜尋：
