### ISSUE TITLE
Add fuzzy search to search bar

### ISSUE THREAD

**Issue by martinctc** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#34]
One potential enhancement in the future would be to make the search more 'fuzzy', e.g. for "HO MAN TIN", some might put "HOMANTIN" (both are known acceptable spellings).

_Originally posted by @martinctc in https://github.com/avisionh/dashboard-hkdistrictcouncillors/pull/23#issuecomment-666730110_

**Comment by avisionh** [comment]
I think I've figured out how we can make this work.

We essentially want to transform (using regex) what the user types into something for the data.

**Comment by avisionh** [comment]
Think this is resolved by the dropdown we already have in the app.
