### ISSUE TITLE
Search by District Councillor name

### ISSUE THREAD

**Issue by martinctc** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#35]
It's a very common situation where people know a name, but want to figure which constituency he/she represents, and what they are up to recently. It is currently not possible to do this via the app.

A feature to let people filter / search by District Councillor name.

**Comment by avisionh** [comment]
Linked to #25. Makes sense to resolve them both together.

**Comment by avisionh** [comment]
Having optional and dependent search boxes aren't super easy! The below doesn't work.

```
selectizeInput(inputId = "input_dropdowntext",
                       label = "請選擇選區 / Please type or select a district",
                       choices = list(Region = sort(unique(data_master_raw$Region)),
                                      Constituency = sort(unique(data_master_raw$DropDownText)),
                                      DC = sort(unique(data_master_raw$DC)))
                       ), #selectizeInput
```

![image](https://user-images.githubusercontent.com/25527485/89127842-d8061580-d4e8-11ea-99e9-8b50bc4a3443.png)

**Comment by avisionh** [comment]
Made this a *spike* because what you want is different ways to filter, but at the same time, these filters can impact the choices in a different filter *e.g. Someone chooses  `Region = "Hong Kong Islands"` and then the list of DCs becomes smaller.

From previous experience in my old company, this was quite difficult to achieve.

**Comment by martinctc** [comment]
> Made this a _spike_ because what you want is different ways to filter, but at the same time, these filters can impact the choices in a different filter *e.g. Someone chooses `Region = "Hong Kong Islands"` and then the list of DCs becomes smaller.
> 
> From previous experience in my old company, this was quite difficult to achieve.

What if we have the region selection available as check boxes, where the default is to have all three boxes (Hong Kong Island, Kowloon, New Territories) checked? The user would expect the list of DCs to become smaller as you un-check more regions, but at the same time the user won't have to 'try' all three regions to get to the DC that they want.

**Comment by avisionh** [comment]
Closing this as I think @martinctc implementation of the region + constituency does a good enough job.
