### ISSUE TITLE
Map blocks fb feed

### ISSUE THREAD

**Issue by ocean0609** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#38]
**Describe the bug**
The map is too big, it blocks the FB feeds

**To Reproduce**
1. Go to 'https://hkdistricts-info.shinyapps.io/dashboard-hkdistrictcouncillors/'
2. Scroll down 
3. See error

**Expected behavior**
The map shouldn't block the FB Feeds

**Screenshots**
<img width="1440" alt="Screenshot 2020-07-31 at 10 35 19" src="https://user-images.githubusercontent.com/67370580/89022683-fdfab100-d354-11ea-84b7-41645640b093.png">

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [Google Chrome]
 - Version [84.0.4147.105 (Official Build) (64-bit)]

**Comment by avisionh** [comment]
Wow, that is a massive bug. No idea how that is happening. Will investigate.

**Comment by martinctc** [comment]
This issue does not always occur - seems to only happen on certain screen sizes. I think the fundamental solution will need to be to make the iframe responsive.

**Comment by ocean0609** [comment]
Forgot to mention, i am using 15" MBP.
