### ISSUE TITLE
Enhancement for Map

### ISSUE THREAD

**Issue by ocean0609** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#41]
**Is your feature request related to a problem? Please describe.**
When i am using the app/site, i don't know what is the purpose of having that map.

**Describe the solution you'd like**
I think it would be better if we can "Zoom In" and "Blink" for selected constituency or we can click on the map to choose which constituency we would like to show on the "Overview".

**Describe alternatives you've considered**
 Just showing the constituency area, but not the HK map.

**Comment by avisionh** [comment]
It's a good suggestion. Will require use of [leaflet](https://rstudio.github.io/leaflet/shiny.html). Not too familiar with it so it'll take more time for me to get round to this.

**Comment by ocean0609** [comment]
I wanna ask how accurate can the tracking cookie pin me down? 
It doesn't track my current location, yea? 
Since not much people knows which constituency they belong to... 
It will be easier if the location tracker works, if not, I am thinking if we can have a blank box for them to type in their address to check.

**Comment by avisionh** [comment]
Good point about people not knowing what constituency they belong to!

Whilst getting a tracking cookie to use the person's geolocation to pin them down requires more effort, we can implement a better search by doing these in the meantime:
- [ ] Regions, #25 
- [ ] DC name, #35
