### ISSUE TITLE
Wrong URL to "Contributor Code of Conduct"

### ISSUE THREAD

**Issue by justin-yim** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#45]
**Describe the bug**
Wrong URL for "Contributor Code of Conduct" on the Construction tab. Now it links to the DC constituency shapefile source. 

**Expected behavior**
Amend to link the right URL

**Screenshots**
<img width="755" alt="Screenshot 2020-08-02 at 18 59 11" src="https://user-images.githubusercontent.com/25984316/89129099-6e8b0480-d4f2-11ea-910e-5b3832de44c1.png">

**Comment by avisionh** [comment]
Good spot! Hopefully fixed it in the linked Pull Request. Awaiting it to be reviewed by @martinctc.
