### ISSUE TITLE
Discuss: Position logo in left sidebar

### ISSUE THREAD

**Issue by avisionh** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#46]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to see the logo more clearly.

**Describe the solution you'd like**
It might be better to have the logo in the bottom-left like below?

![image](https://user-images.githubusercontent.com/25527485/89129275-02a99b80-d4f4-11ea-8929-fb64c0b09771.png)

**Describe alternatives you've considered**
Where it is currently positioned is quite small and hard to see.

**Additional context**
Website is [here](https://hssgenomics.shinyapps.io/RNAseq_DRaMA/).

Code base is [here](https://gitlab.com/hssgenomics/Shiny).

**Comment by ocean0609** [comment]
![Z9TLcDd](https://user-images.githubusercontent.com/67370580/89485385-3e35b580-d7d3-11ea-9b39-3b1d36fb0cd2.png)
