### ISSUE TITLE
External: Review typeform survey

### ISSUE THREAD

**Issue by avisionh** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#48]
# Summary
@chautinsum has helpfully created a wonderful TypeForm survey:
- https://admin.typeform.com/form/gFHC02gE/create

Let's all review it and provide her with some feedback.

## Note
To access the TypeForm, please use the Gmail account details.

**Comment by avisionh** [comment]
Short and sweet, I like it! Just a couple of questions:
1. What's question 3?
1. Should we make any of the questions mandatory?
1. For the occupation, should provide options like journalist, district councillor, analyst, other etc.? 
1. We should include a note on data handling to comply with GDPR. In particular, that we will handle their data safely and securely, and won't share with third parties. I can draft something up.

**Comment by ocean0609** [comment]
Good one @chautinsum 
I think we will need Chinese Translation.
Let me know when there is a final version of the survey, thanks!

**Comment by avisionh** [comment]
@chautinsum said she will create a Chinese version!

**Comment by chautinsum** [comment]
@avisionh @ocean0609 Just finished the chinese version! Please have a look :)
