### ISSUE TITLE
External: Share with target audience

### ISSUE THREAD

**Issue by avisionh** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#52]
# Summary
Should start sharing the website with people like DCs, reporters and academics to gain early feedback and thereby improve the website before we release more formally to general public.

**Comment by avisionh** [comment]
We should release this after we get the Typeform done so we can gather feedback from interested technical users.

**Comment by ocean0609** [comment]
Okay!

**Comment by ocean0609** [comment]
Are we going to prepare a survey for the users as well?

**Comment by martinctc** [comment]
> Are we going to prepare a survey for the users as well?

We will aim to have two surveys available: one for 'key users' (i.e. DCs, reporters), and another one for general public! @chautinsum is on this 😃

**Comment by avisionh** [comment]
Closing this as this will be captured on the Trello board.
