### ISSUE TITLE
Discuss: Do we need funding?

### ISSUE THREAD

**Issue by avisionh** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#53]
# Summary
Should we start setting up links and the structure to accept sponsorship for possible expected costs related to the below?
- Website hosting 
    + Currently, we can host for free for up to 30 hours per month
- Custom domain names
- Additional functionality for TypeForm
- Google Analytics
    + Could unlock additional insights by paying some money and being able to access the data.
- Opportunity cost
   + Are we happy to continue working on this for free? It's okay to seek some sort of reimbursement as you may think you could have spent your time better on other activities.

**Comment by ocean0609** [comment]
I think we need fundings even we are okay to work for free..
With the funds we can upgrade/unlock features for this or maybe future projects?

**Comment by martinctc** [comment]
I'm not against getting funding as long as it doesn't impact on our neutrality and has no implications on conflict of interest for the collaborators. Otherwise, any extra money that can be spent on domain names and server time would always be helpful.

**Comment by avisionh** [comment]
Fab, we can set up some sponsorship on the organisation then.

**Comment by avisionh** [comment]
Closing this because it's going to be captured on the Trello board.
