### ISSUE TITLE
Tutorial Page Bug?

### ISSUE THREAD

**Issue by ocean0609** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#72]
**Describe the bug**
Bug found when clicking the "Tutorial" button

**To Reproduce**
1. Click on 'Tutorial'
2. See error

**Screenshots**
![Bug report](https://user-images.githubusercontent.com/67370580/91650233-8a60d680-eaaf-11ea-9356-7d72e3250f62.png)

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser: Google Chrome
 - Version 84.0.4147.135

**Comment by avisionh** [comment]
Good spot. This one frustrated me too. The tl;dr here is that I've tried my best to keep that sidebar open when going through the tutorial, but when accessing the tutorial on mobiles, that sidebar takes up so much room that you cannot see the tutorial for other steps. 

Thus to view the tutorial relatively nicely on mobiles such that the sidebar doesn't obscure everything, I needed to collapse the sidebar when the user clicks *Tutorial*. However, it came at the cost of that step (one you highlighted) looking funny.

Thus, unfortunately, I don't think there's an easy way around this...
