### ISSUE TITLE
Translations for Tips

### ISSUE THREAD

**Issue by ocean0609** [Hong-Kong-Districts-Info/dashboard-hkdistrictcouncillors#73]
A)
Tip: Dropdown 
You can either:
1. select from the dropdown list, or
2. type the name of your constituency in here.

提示：下拉列表
您可以：
1. 從下拉列表中選擇，或
2. 在此處輸入您的選區名稱。

B)
Tip: Facebook click-through
Click on this to access their public FB page.

提示：面書按鍵
單擊此以訪問議員公共面書頁面。

C)
Press the icon of the three lines in the top-left to access the navigation sidebar.

按左上方的三線圖標，以打開側欄。

**Comment by avisionh** [comment]
Thanks! I've implemented these now but the FB one needs updating to say website instead. I've mentioned it in the attached PR, #69.
